### ISSUE TITLE
what is the latest HTMLCoin wallet?

### ISSUE THREAD

**Issue by richardpor** [HTMLCOIN/HTMLCOIN#93]

**Comment by richardpor** [comment]
I am using HTMLCOIN wallet 2.5.1 but it is not connecting to peers. I downloaded HTMLCOIN wallet 2.5.2 but it has no executable file. I am confused!

**Comment by denuoweb** [comment]
2.5.1 is fine to use. you might need to reinstall to reconnect to peers

**Comment by richardpor** [comment]
Hi Jaron. Thanks for replying! Ok, I am using 2.5.1 now but it is stuck and
hasn't updated from June. It was working fine for maybe 3 years. I am
generally tech savvy, but concerned here. So is it safe to delete the app
and then reinstall it? I am concerned about loosing my contact with the
htmlcoin world! Or should I reinstall and simply override what I have now?

I am confused about that.

Thanks!

Richard

**Comment by denuoweb** [comment]
I'm sure that I don't have to tell you to back up your wallet, and you shouldn't take my word for it. So as an exercise, you should go to a different computer, download HTMLCOIN and try to import your backed up wallet file to see if it works. Once you verify that as long as you have a backed up wallet file, you can restore your account on any computer anywhere in the world, then go back to your normal computer and remove and reinstall the blockchain. Then import your backed up wallet like in your exercise. Regardless, this is not the place to be getting technical support help with your wallet, the telegram channel is more appropriate.  https://t.me/officialhtmlcoin Although I guarantee they won't answer your question on why the 2.5.2 and 2.5.3 don't have executables, the reason is the foundation isn't paying for a developer to provide them, but anything beyond 2.5.1 right now is only for developers anyway so regular users don't actually need to use any version beyond 2.5.1.
